---
kind: pipeline
name: php7.2-alpine3.8

steps:
  - name: cli
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/php
      context: 7.2/alpine/3.8/cli/
      dockerfile: 7.2/alpine/3.8/cli/Dockerfile
      tags:
        - '7.2.16-cli-alpine3.8'
        - '7.2-cli-alpine3.8'
        - '7.2.16-alpine3.8'
        - '7.2-alpine3.8'

  - name: fpm
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/php
      context: 7.2/alpine/3.8/fpm/
      dockerfile: 7.2/alpine/3.8/fpm/Dockerfile
      tags:
        - '7.2.16-fpm-alpine3.8'
        - '7.2-fpm-alpine3.8'

  - name: supervisor
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/php
      context: 7.2/alpine/3.8/supervisor/
      dockerfile: 7.2/alpine/3.8/supervisor/Dockerfile
      tags:
        - '7.2.16-supervisor-alpine3.8'
        - '7.2-supervisor-alpine3.8'

  - name: aio
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: dockage/php
      context: 7.2/alpine/3.8/aio/
      dockerfile: 7.2/alpine/3.8/aio/Dockerfile
      tags:
        - '7.2.16-aio-alpine3.8'
        - '7.2-aio-alpine3.8'

---
kind: pipeline
name: notify

steps:
  - name: microbadger
    image: plugins/webhook
    settings:
      urls:
        - https://hooks.microbadger.com/images/dockage/php/9f9k6_coS0GVJ4QWQYeTKJLIg2g=

depends_on:
  - php7.2-alpine3.8
